# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: green umbrella
description: >- # this means to ignore newlines until "baseurl:"
  신입 백엔드 개발자 강은영의 포트폴리오 페이지
baseurl: "/" # the subpath of the site
url: "https://greenkey20.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic-key.jpeg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /    
    - name: Projects  # 새로 추가
      slug: /projects
    - name: Stories
    - name: CV

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: greenkey20@naver.com
      link: mailto:greenkey20@naver.com
  follow:
    - name: GitHub
      link: https://github.com/greenkey20
    - name: blog
      link: https://greenkey20dev.tistory.com/
    - name: LinkedIn
      link: http://www.linkedin.com/in/greenkey20

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
